name: Publish

# Only run when code pushed to master
on:
  push:
    tags:
    - prod/*
  inputs:
    name:
      description: 'What's your name?'
      default: 'No name provided'
    runs:
      using: "composite"
      steps:
        - run: echo Hello ${{ inputs.name }}.
          shell: bash
        - run: echo "Awesome as to meet you!"
          shell: pwsh 
