name: Composite Run Setps
on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
     - master
       - 

jobs:
  build:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2
    - uses: octocat/say-hello@v1
      with:
        name: OctoCat
      
